import { readdir, readFile, mkdir, writeFile, appendFile, access } from "node:fs/promises";
import { join, relative, dirname } from "node:path";
import type { AstroIntegration } from "astro";

function stripFrontmatter(content: string): string {
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  return match ? content.slice(match[0].length).trimStart() : content;
}

async function collectMarkdown(dir: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectMarkdown(full)));
    } else if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) {
      files.push(full);
    }
  }
  return files;
}

export default function markdownPages(): AstroIntegration {
  let siteUrl = "";
  return {
    name: "markdown-pages",
    hooks: {
      "astro:config:setup": ({ config }) => {
        siteUrl = config.site?.replace(/\/$/, "") ?? "";
      },
      "astro:build:done": async ({ dir }) => {
        const docsRoot = new URL("../content/docs/", import.meta.url)
          .pathname;
        const outDir = new URL(".", dir).pathname;
        const files = await collectMarkdown(docsRoot);
        const mdPaths: string[] = [];

        for (const file of files) {
          const rel = relative(docsRoot, file).replace(/\.mdx?$/, ".md");
          const dest = join(outDir, rel);
          const content = await readFile(file, "utf-8");
          await mkdir(dirname(dest), { recursive: true });
          await writeFile(dest, stripFrontmatter(content));
          mdPaths.push(rel);
        }

        mdPaths.sort();
        const links = mdPaths
          .map((p) => `- [${p}](${siteUrl}/${p})`)
          .join("\n");
        const section = `\n## Individual Pages (Markdown)\n\n${links}\n`;

        // llms.txt is produced by starlight-llms-txt; appending depends on its
        // astro:build:done hook running before ours. Guard against it being
        // absent so a missing/renamed dependency fails loudly instead of
        // silently writing a partial file.
        const llmsTxt = join(outDir, "llms.txt");
        try {
          await access(llmsTxt);
        } catch {
          throw new Error(
            `markdown-pages: expected ${llmsTxt} to exist (generated by starlight-llms-txt) before appending the Markdown page index.`,
          );
        }
        await appendFile(llmsTxt, section);
      },
    },
  };
}
