import { Glob } from "bun";
import path from "node:path";

export interface SkillDoc {
  kind: "subcommand" | "reference";
  description: string;
  content: string;
}

const root = path.resolve(import.meta.dir, "..");
const skillsDir = path.join(root, "skills");

function firstHeading(md: string): string {
  for (const line of md.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    if (t.startsWith("#")) return t.replace(/^#+\s*/, "").trim();
    if (t.startsWith("---")) continue; // frontmatter fence
    return t;
  }
  return "";
}

export async function collectSkills(): Promise<{
  root: string;
  skills: Record<string, SkillDoc>;
}> {
  const glob = new Glob("**/*.md");
  let rootContent = "";
  const skills: Record<string, SkillDoc> = {};

  for await (const rel of glob.scan(skillsDir)) {
    if (path.basename(rel) === "README.md") continue;
    const abs = path.join(skillsDir, rel);
    const content = await Bun.file(abs).text();

    if (rel === "SKILL.md") {
      rootContent = content;
      continue;
    }

    const name = path.basename(rel, ".md");
    const dir = rel.split(path.sep)[0];
    const kind =
      dir === "subcommands" ? "subcommand" :
      dir === "references" ? "reference" : null;
    if (!kind) throw new Error(`gen-skills: unexpected skill path "${rel}"`);

    if (skills[name]) {
      throw new Error(`gen-skills: duplicate skill name "${name}" (from ${rel})`);
    }
    skills[name] = { kind, description: firstHeading(content), content };
  }

  if (!rootContent) throw new Error("gen-skills: skills/SKILL.md not found");
  return { root: rootContent, skills };
}

export async function generate(): Promise<string> {
  const { root, skills } = await collectSkills();
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/gen-skills.ts — do not edit.",
    "export interface SkillDoc {",
    '  kind: "subcommand" | "reference";',
    "  description: string;",
    "  content: string;",
    "}",
    `export const SKILL_ROOT: string = ${JSON.stringify(root)};`,
    "export const SKILLS: Record<string, SkillDoc> = {",
  ];
  for (const [name, doc] of Object.entries(skills).sort()) {
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(doc)},`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

if (import.meta.main) {
  const out = path.join(root, "packages", "cli", "src", "skills.generated.ts");
  await Bun.write(out, await generate());
  console.log(`wrote ${path.relative(root, out)}`);
}
